# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id')),
                ('bookname', models.CharField(blank=True, max_length=50, verbose_name='bookname')),
                ('unit', models.IntegerField(verbose_name='unit')),
                ('word', models.CharField(blank=True, max_length=50, verbose_name='word')),
                ('meaning', models.CharField(blank=True, max_length=50, verbose_name='meaning')),
            ],
            options={
                'verbose_name_plural': 'learn_word',
                'verbose_name': 'learn_word',
            },
        ),
    ]
