# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-30 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20180630_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='isfinished',
        ),
    ]
