# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-30 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_remove_record_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='isfinished',
            field=models.IntegerField(default=0, verbose_name='isfinished'),
        ),
    ]
