# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-01 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20180630_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='isfinished',
        ),
        migrations.AddField(
            model_name='record',
            name='islearned',
            field=models.IntegerField(default=0, verbose_name='islearned'),
        ),
        migrations.AddField(
            model_name='record',
            name='learntime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='learntime'),
        ),
    ]
