# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('unit', models.IntegerField(verbose_name='unit')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='author')),
                ('info', models.CharField(blank=True, max_length=200, verbose_name='info')),
            ],
            options={
                'verbose_name_plural': 'books_list',
                'verbose_name': 'books_list',
            },
        ),
    ]
