# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-30 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, verbose_name='userid')),
                ('bookid', models.IntegerField(blank=True, verbose_name='bookid')),
                ('unit', models.IntegerField(blank=True, verbose_name='unit')),
                ('isreviewed', models.IntegerField(default=0, verbose_name='isreviewed')),
            ],
            options={
                'verbose_name': 'review_record',
                'verbose_name_plural': 'review_record',
            },
        ),
    ]
