# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-01 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='reviewtime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='reviewtime'),
        ),
    ]
