# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-28 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180628_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
    ]
